// Copyright 2026 Qilimanjaro Quantum Tech
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "environment.h"

// GCOV_EXCL_BR_START

EnvironmentCpp::EnvironmentCpp(int n_system_qubits_, int n_environment_qubits_, const SparseMatrix& hamiltonian_, const std::vector<SparseMatrix>& jump_operators_, const SparseMatrix& initial_state_)
    : n_system_qubits(n_system_qubits_), n_environment_qubits(n_environment_qubits_), hamiltonian(hamiltonian_), jump_operators(jump_operators_), initial_state(initial_state_) {}

int EnvironmentCpp::get_n_system_qubits() const {
    return n_system_qubits;
}

int EnvironmentCpp::get_n_environment_qubits() const {
    return n_environment_qubits;
}

int EnvironmentCpp::get_n_total_qubits() const {
    return n_system_qubits + n_environment_qubits;
}

SparseMatrix EnvironmentCpp::attach_to(const SparseMatrix& rho_system) const {
    /*
    Build the initial state of the full register, with the environment after the system.

    Args:
        rho_system (SparseMatrix): The system statevector or density matrix.

    Returns:
        SparseMatrix: The density matrix rho_system (x) rho_environment.
    */
    // TODO: promote a statevector to a density matrix, then kron with initial_state
    return rho_system;
}

DenseMatrix EnvironmentCpp::trace_out(const DenseMatrix& rho, bool state_is_trajectories) const {
    /*
    Trace out the environment qubits, leaving the system state.

    Args:
        rho (DenseMatrix): The state of the full register.
        state_is_trajectories (bool): Whether rho holds Monte Carlo trajectories (one statevector per column).

    Returns:
        DenseMatrix: The reduced state of the system qubits, in the same format as rho.
    */
    // TODO: partial trace over the last n_environment_qubits (per trajectory, if state_is_trajectories)
    return rho;
}

void EnvironmentCpp::add_to_evolution(std::vector<SparseMatrix>& hamiltonians, std::vector<std::vector<double>>& parameters_list, NoiseModelCpp& noise_model_cpp) const {
    /*
    Add the environment to an evolution on the full register: the coupling Hamiltonian with a
    constant unit coefficient at every step, and the environment jump operators.

    Args:
        hamiltonians (std::vector<SparseMatrix>&): The Hamiltonians of the evolution, on the full register.
        parameters_list (std::vector<std::vector<double>>&): The per-step coefficient of each Hamiltonian.
        noise_model_cpp (NoiseModelCpp&): The Markovian noise of the evolution, on the full register.
    */
    // TODO: push hamiltonian with a coefficient series of ones, add_jump_operator for each jump operator
}

void circuit_to_schedule(const std::vector<Gate>& gates, const std::map<std::string, float>& gate_durations, int n_total_qubits, double dt, std::vector<SparseMatrix>& hamiltonians, std::vector<std::vector<double>>& parameters_list, std::vector<double>& step_list) {
    /*
    Lower a circuit to a piecewise-constant schedule, so it can be evolved together with the environment.
    Gates run one after another; gate k is generated by H_k = i log(U_k) / T_k during its duration T_k, and
    every other qubit idles meanwhile.

    Args:
        gates (std::vector<Gate>): The gates of the circuit, in order.
        gate_durations (std::map<std::string, float>): Per-gate noise key -> execution time (see resolve_gate_durations).
        n_total_qubits (int): The number of qubits of the full register.
        dt (double): The maximum time step within a gate.
        hamiltonians (std::vector<SparseMatrix>&): Output, the generator of each gate on the full register.
        parameters_list (std::vector<std::vector<double>>&): Output, 1 during the gate's duration and 0 elsewhere.
        step_list (std::vector<double>&): Output, the time points of the schedule.
    */
    // TODO: look up each gate's duration by NoiseModelCpp::make_gate_key(name, number of controls),
    //       matrix logarithm of its full matrix, split each duration into ceil(T_k / dt) steps
    // TODO: later, schedule gates on disjoint qubits in parallel (layers) instead of one after another
}

// GCOV_EXCL_BR_STOP
