name: Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - "opened"
      - "reopened"
      - "synchronize"
      - "ready_for_review"

jobs:
  code-quality:
    name: Code Quality for Python ${{ matrix.python-version }}
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      HOME_REPO: /home/repo

    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          fetch-depth: 1

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d  # v10.0.1
        with:
          enable-cache: true
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: |
          uv sync --frozen --group dev --extra all-cu13 \
            -Ccmake.build-type=Debug \
            -Ccmake.define.CMAKE_CXX_FLAGS_DEBUG=-O0
          echo "VIRTUAL_ENV=$PWD/.venv" >> "$GITHUB_ENV"
          echo "$PWD/.venv/bin" >> "$GITHUB_PATH"

      - name: Ruff
        run: ruff check --output-format=github .

      - name: Format
        run: ruff format --diff --output-format=github .

      - name: Type Checking
        run: ty check --output-format=github

      - name: Cpp Linter
        uses: cpp-linter/cpp-linter-action@cab1143a2c149bc41e85b070a9de81716974c18f  # v2.21.0
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: 'file'
          tidy-checks: ''
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
