name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - "opened"
      - "reopened"
      - "synchronize"
      - "ready_for_review"

jobs:
  tests:
    name: Testing for Python ${{ matrix.python-version }}
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 5

    env:
      HOME_REPO: /home/repo

    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock
          python-version: ${{ matrix.python-version }}

      - name: Install qilisdk
        run: |
          uv -v sync --group dev --extra all-cu13 -Ccmake.define.tests=ON -Ccmake.build-type=Debug -Ccmake.define.coverage=ON --reinstall
          echo "VIRTUAL_ENV=$PWD/.venv" >> "$GITHUB_ENV"
          echo "$PWD/.venv/bin" >> "$GITHUB_PATH"

      - name: Run Python tests
        run: pytest --cov=qilisdk --cov-report=xml --cov-report=term-missing --junitxml=junit.xml -o junit_family=legacy tests/unit_python/

      - name: Run C++ tests
        run: |
          GCOV_PREFIX=$(pwd)/tests/unit_cpp/coverage GCOV_PREFIX_STRIP=5 ./tests/unit_cpp/test_cpp
          gcovr --exclude '.*googletest.*' --exclude '/usr/.*' --gcov-ignore-errors=all --exclude-unreachable-branches --exclude-throw-branches --xml coverage_cpp.xml

      - name: Combine coverage reports
        run: gcovr --gcov-ignore-errors=all --xml combined_coverage.xml --cobertura-add-tracefile coverage.xml --cobertura-add-tracefile coverage_cpp.xml

      - name: Output the coverage directory for debugging
        run: ls -R tests/unit_cpp/coverage/

      - name: Print the working directory for debugging
        run: pwd

      - name: Upload coverage to Codecov
        if: ${{ matrix.python-version == '3.13' }}
        uses: codecov/codecov-action@v5
        with:
          files: combined_coverage.xml
          disable_search: true
          token: ${{ secrets.CODECOV_TOKEN }}
      
      - name: Upload test results to Codecov
        if: ${{ !cancelled() && matrix.python-version == '3.13' }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}