name: Tests with Tox

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - "opened"
      - "reopened"
      - "synchronize"
      - "ready_for_review"

jobs:
  tox:
    name: Test with Tox
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"

      - name: Install Python
        run: uv python install --python-preference only-managed 3.10 3.11 3.12 3.13

      - name: Install tox
        run: uv tool install --python-preference only-managed --python 3.13 tox --with tox-uv

      - name: Run tests
        run: tox run-parallel
