name: Tox

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - "opened"
      - "reopened"
      - "synchronize"
      - "ready_for_review"

jobs:
  tox:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 5

    env:
      HOME_REPO: /home/repo

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install tox
        run: uv tool install tox

      - name: Run tests
        run: uv run tox
